apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
      - name: regdoc
      containers:
      - name: mysql
        image: mysql:8.0.19
        ports:
        - containerPort: 3306
        env:
        - name: TZ
          value: "Europe/Rome"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lamp-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef:
              name: lamp-secret
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: lamp-secret
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
          