apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web-server
    spec:
      containers:
        - image: yok007/web-server:latest
          name: web-server
          ports:
            - containerPort: 80
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
